export const starterFoods = [
  {
    category: "protein",
    categoryLabel: "Protein",
    name: "Chicken breast",
    slug: "chicken-breast",
    servingQuantity: "100",
    servingUnit: "g" as const,
    caloriesKcal: "165",
    proteinG: "31",
    carbohydrateG: "0",
    fatG: "3.6",
  },
  {
    category: "protein",
    categoryLabel: "Protein",
    name: "Eggs",
    slug: "eggs",
    servingQuantity: "2",
    servingUnit: "item" as const,
    caloriesKcal: "144",
    proteinG: "12.6",
    carbohydrateG: "0.8",
    fatG: "9.5",
  },
  {
    category: "carbohydrates",
    categoryLabel: "Carbohydrates",
    name: "Oats",
    slug: "oats",
    servingQuantity: "40",
    servingUnit: "g" as const,
    caloriesKcal: "152",
    proteinG: "5.1",
    carbohydrateG: "27",
    fatG: "3",
  },
  {
    category: "carbohydrates",
    categoryLabel: "Carbohydrates",
    name: "Cooked rice",
    slug: "cooked-rice",
    servingQuantity: "100",
    servingUnit: "g" as const,
    caloriesKcal: "130",
    proteinG: "2.7",
    carbohydrateG: "28",
    fatG: "0.3",
  },
  {
    category: "fruit",
    categoryLabel: "Fruit",
    name: "Banana",
    slug: "banana",
    servingQuantity: "1",
    servingUnit: "item" as const,
    caloriesKcal: "105",
    proteinG: "1.3",
    carbohydrateG: "27",
    fatG: "0.4",
  },
  {
    category: "fats",
    categoryLabel: "Fats",
    name: "Peanut butter",
    slug: "peanut-butter",
    servingQuantity: "1",
    servingUnit: "tbsp" as const,
    caloriesKcal: "94",
    proteinG: "4",
    carbohydrateG: "3.2",
    fatG: "8",
  },
  {
    category: "dairy",
    categoryLabel: "Dairy",
    name: "Plain Greek yoghurt",
    slug: "plain-greek-yoghurt",
    servingQuantity: "170",
    servingUnit: "g" as const,
    caloriesKcal: "100",
    proteinG: "17",
    carbohydrateG: "6",
    fatG: "0.7",
  },
  {
    category: "protein",
    categoryLabel: "Protein",
    name: "Canned tuna",
    slug: "canned-tuna",
    servingQuantity: "100",
    servingUnit: "g" as const,
    caloriesKcal: "116",
    proteinG: "25.5",
    carbohydrateG: "0",
    fatG: "0.8",
  },
] as const;
